version: '3'
services:
  nei:
    build: .
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - redis
      - mongodb
      - mysql
    links:
      - redis
      - mongodb
      - mysql
  redis:
    image: redis:5-alpine
    restart: always
  mongodb:
    image: mongo:3.4
    restart: always
    volumes:
      - ~/.nei/mongodb:/data/db
  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ~/.nei/mysql:/var/lib/mysql
      - ./docs:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: nei-test
      MYSQL_ROOT_PASSWORD: 123456
